# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('api', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(default='a', on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
            preserve_default=False,
        ),
    ]
