# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
