# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='uuid',
            new_name='number',
        ),
        migrations.AddField(
            model_name='room',
            name='token',
            field=models.CharField(default='a', max_length=18),
            preserve_default=False,
        ),
    ]
